name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ['ubuntu-latest', '18.04']
        node_version: ['12']
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}   
    
  build:
    needs: test
    runs-on: ${{ matrix.OS }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name${{ matrix.OS }}:$(date +%s) 
