name: RENDER

on:
  push:
    branches: [ "master" ]

jobs:

  build:
  
    strategy:
      matrix:
        OS: ['ubuntu-latest']

    runs-on: ${{ matrix.OS }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Render Deployment
      uses: sws2apps/render-deployment@v1.2.0
      with:
          # The Service ID of your Render service
          serviceId: ChWJVifi0PQ    
